pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'jenkins/test-caching'
        }
    }

    stages {
        stage('Build') {
            steps {
                script {
                    sh '''#!/bin/bash
                        echo "hello world"
                    '''
                }
            }
        }
    }
}