pipeline {
    agent { dockerfile true }

    stages {
        stage('Build') {
            steps {
                script {
                    sh '''#!/bin/bash
                        echo "hello world"
                    '''
                }
            }
        }
    }
}